### ISSUE TITLE
upload file

### ISSUE THREAD

**Issue by saihoooooooo** [ktty1220/cheerio-httpcli#10]
フォームのsubmit時に<input type="file">に対してローカルのファイル（画像など）をアップロードする方法はありますか？
少し試行錯誤してみたんですがうまくいかず
現状不可でしょうか

**Comment by ktty1220** [comment]
残念ながら今のところはアップロード（input[type=file]）には対応していないです。
cheerio本体も見てみましたが対応していない感じです（まあHTMLのパースが主目的なのでそりゃそうだなって感じですが）。

ファイルのアップロードをエミュレートするような機能は多分実装できると思いますが、色々と調査しないといけないのですぐというわけにはいきませんが、今後の予定として検討しておきます。

ありがとうございました。
