### ISSUE TITLE
プロキシを使いたいんですが、何か方法がありますでしょうか。

### ISSUE THREAD

**Issue by kxx129** [ktty1220/cheerio-httpcli#13]
お疲れ様です、ゆです。
cheerio-httpcliモジュールのご提供、ありがとうございます。とても便利なモジュールと思ってます。
ご提供して頂いたcheerio-httpcliモジュールを使って、ウェブスクレイピングツールを作ると検討しています。
プロキシを使いたいんですが、何かいい方法がありますでしょうか。ご教示いただければ幸いと思います。
ちなみに、ベースモジュールのrequestの方はいくつ方法があるらしいです。
例えば：
http://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client
https://github.com/request/request/issues/894
お手数済みませんがよろしくお願いいたします。

**Comment by ktty1220** [comment]
requestモジュールをのぞいてみましたが、`HTTP_PROXY`環境変数が指定されていればそれを使用するみたいです。

ちょっと試してみました。

```js
process.env.HTTP_PROXY = 'http://プロキシサーバーのアドレス:ポート/';

var client = require('cheerio-httpcli');
client.fetch('http://www.ugtop.com/spill.shtml', function (err, $, res, body) {
  console.log($('table').eq(1).find('tr').eq(3).find('td').eq(1).text().trim());
});
```

`REMOTE_ADDR`がプロキシサーバーのアドレスになっていたのでこれでいけそうな気がしますがどうでしょうか。

**Comment by kxx129** [comment]
process.env.HTTP_PROXY = 'http://プロキシサーバーのアドレス:ポート/';
なるほど。大変助かりました。
ご教示を頂き、ありがとうございます。

**Comment by tuclicks** [comment]
上記の方法でプロキシがうまく動作しません。

firebase cloud function での basic認証付きのproxyについて
```
process.env.HTTP_PROXY = `http://${username}:${password}@${host}:${port}\
//or
process.env.HTTP_PROXY = `http://${host}:${port}`
client.set('headers', {
   Authorization: 'Basic ' + Buffer.from(`${username}:${password}`).toString('base64')
})
```

いづれの方法でもbasic認証がかけられているプロキシからアクセスすることができませんでした。
環境はfirebase function (emulator or production) です。

**Comment by ktty1220** [comment]
調べてみた感じでは、`process.env.HTTP_PROXY = http://${username}:${password}@${host}:${port}`で設定は正しそうですが、いくつか確認点があります。

1. Firebaseのプランは有料プランですか？無料プランだと外部ネットワークへのアクセスに制限があるそうです（[参考](https://ja.stackoverflow.com/questions/39116/actions-on-google-%E3%81%A7%E3%81%AE-cheerio-httpcli%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%9F%E3%82%B9%E3%82%AF%E3%83%AC%E3%82%A4%E3%83%94%E3%83%B3%E3%82%B0%E3%81%A7-fetch%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%8C%E5%8B%95%E3%81%8B%E3%81%AA%E3%81%84)）。
2. Firebase上ではなく、ローカル環境で実行した場合にも失敗しますか？
3. アクセスできなかったという状況の詳細について、エラーが発生している場合はエラーメッセージをお知らせください。エラーが出ていない場合は詳しい状況を教えてください（いつまで経ってもリクエスト処理が戻ってこない、処理結果が空になっている、など）。

**Comment by tuclicks** [comment]
ご返信ありがとうございます。
再度確認したところ正常に動作しておりました。
`process.env.HTTP_PROXY = http://${username}:${password}@${host}:${port}`

ESOCKETTIMEDOUTエラーが出ていたのですが、最初にhttp抜きのproxyを登録したので、以前のprocess.envのインスタンスが残ってた？せいかもしれません。
わざわざ調べていただきありがとうございます。助かりました。
