### ISSUE TITLE
JavaScriptファイル `<script>` やCSSファイル `<link>` のsrcやhrefのURLも絶対パスで取得したい

### ISSUE THREAD

**Issue by k1LoW** [ktty1220/cheerio-httpcli#21]
@ktty1220 

私が想定している用途で、JavaScriptファイル `<script>` やCSSファイル `<link>` のsrcやhrefのURLも絶対パスで取得したいというモチベーションがあります。

具体的には https://github.com/ktty1220/cheerio-httpcli/blob/master/lib/cheerio/url.js の拡張になると思っているのですが、この提案についてどう思われますか？

もし cheerio-httpcli のコンセプト上問題のない提案なのであればPullRequestを作成したいと思っています。

> 他のIssueと同様に日本語で記述しましたが問題ありましたら書き直します

**Comment by ktty1220** [comment]
よろしいのではないかと思います。:+1:
PRお待ちしてます。
