### ISSUE TITLE
擬似セレクタを利用できない

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [ktty1220/cheerio-httpcli#27]
擬似セレクタ(:first-childや:not())を利用しようとするとエラーになり、クラッシュする

**Comment by ktty1220** [comment]
「クラッシュ」と呼ばれる現象の詳細について確認したいのですが、

* 疑似セレクタを使用する行に入った段階でエラーメッセージも表示されずにプログラムが終了する
かつ
* 該当処理の直前行までは動作していることは確実である

という事でしょうか。

もし「エラーになり」という部分で何かしらのエラーメッセージが出ているのであればそれを教えてもらえますか。

また、こちらで簡単な疑似セレクタを使用した処理を試してみたところ、特にそのような現象は起きなかったので、差し支えなければ

* 使用しているOSとNode.jsのバージョン
* 実際に問題が発生したスクリプトの内容（状況を再現できる状態のもの）

を教えてもらってもよいですか。

**Comment by HIBIKI-CUBE** [comment]
こちらから聞いておきながら返信が遅くなってしまいすみません。あのあと色々と試したのですが私のミスだったのか今は大丈夫になりました。
また発生し次第スクリーンショット等を添えてお伝えしたいと思います。

また、コードですがとてもお見せできるようなものではないのですが、こちらのリポジトリにて公開しております。
https://github.com/HIBIKI-CUBE/VAWN

**Comment by ktty1220** [comment]
了解しました。:ok_hand:
一旦こちらのIssueはCloseしますので、また発生したら改めてお知らせください。
