### ISSUE TITLE
海外サーバーに置いたアプリからのアクセス

### ISSUE THREAD

**Issue by parmalatinter** [ktty1220/cheerio-httpcli#29]
cheerio-httpcliは大変使いやすく、重宝しております。
ありがとうございます。

表記の件ですが海外サーバー（米国 heroku）に設置したアプリからですと、IPアドレスが米国になってしまい米国版サイトが表示されてしまいます。
IPアドレスを偽装する方法や今後そのような機能開発などありましたらご教授お願い致します。

**Comment by parmalatinter** [comment]
参考サンプル
https://google-shopping-scraping.herokuapp.com/?name=ps3

**Comment by ktty1220** [comment]
IPアドレスの偽装はJavaScriptレベルだと難しいと思いますので、以下のようにAccept-Languageヘッダをセットして日本語環境であると明示的に指定してみるのはどうでしょうか（この方法でGoogleは行けました）。

```js
var cli = require('cheerio-httpcli');

// ↓この部分
cli.set('headers', {
  'accept-language': 'ja-JP'
});
// ↑この部分

cli.fetch('https://www.google.co.jp/')
.then( 〜
```

ブラウザから送信されたAccept-Languageヘッダを無視してIPアドレスで言語を強制的に振り分けるような乱暴なサイトだとこれでも無理なので、日本国内のProxyサーバーを経由するなどといった方法が必要になります。

Proxy経由の接続については[こちら](https://github.com/ktty1220/cheerio-httpcli/issues/13)をご覧ください。

**Comment by parmalatinter** [comment]
ご返事ありがとう御座います。

そちらのコードを追加して試しましたが英語で表示されてしまいました。
一応、accept-languagをクロームで使用している下記に変えてもダメでした。

accept-language: ja,en-US;q=0.9,en;q=0.8,es;q=0.7

下記のサイトをスクレイピングしています。
https://www.google.co.jp/search?q=ps3&oq=ps3&source=lnms&tbm=shop&sa=X&start=0

日本国内のサーバーにアプリを置くのが無難ですかね。

**Comment by parmalatinter** [comment]
<img width="1280" alt="2018-03-10 14 45 51" src="https://user-images.githubusercontent.com/6459902/39612763-1b70be16-4f9d-11e8-849c-5bf8f85be6f2.png">

**Comment by parmalatinter** [comment]
<img width="1138" alt="2018-05-04 13 09 31" src="https://user-images.githubusercontent.com/6459902/39612774-318deade-4f9d-11e8-8e0d-a4a39f6e960a.png">

**Comment by parmalatinter** [comment]
<img width="1026" alt="2018-05-04 13 27 17" src="https://user-images.githubusercontent.com/6459902/39612962-ebae0754-4f9e-11e8-9f53-0aa33d8f0998.png">

**Comment by parmalatinter** [comment]
下記は全て試しました。
'accept-language': 'ja-JP'
'accept-language': 'ja'
'accept-language': 'ja,en-US;q=0.9,en;q=0.8,es;q=0.7'

**Comment by ktty1220** [comment]
ちょっと試してみてもらいたいことがあるのですが、

```js
var cli = require('cheerio-httpcli');

cli.set('headers', {
  'accept-language': 'ja-JP'
});

// ↓この部分
cli.set('debug', true);
// ↑この部分

cli.fetch('https://www.google.co.jp/')
.then( 〜
```

上記のようにデバッグ機能をONにすると、`fetch`時の内部パラメータが表示されるようになります。

![_001](https://user-images.githubusercontent.com/2086147/39613748-ac1948aa-4fa4-11e8-9009-1d88a6181bba.png)

このデバッグ情報のAccept-Languageが日本のものに変更されているかどうか確認してもらってもよいでしょうか。

ちょっと調べた所、以下のような情報がありました。

http://min117.hatenablog.com/entry/2017/02/08/221931

上記の記事を見る限り、やはり利用しているアクセス元（IPアドレス）よりも言語設定が優先して判定されているようなので、Accept-Languageが無視されるという今回の現象はいまいち腑に落ちません。

もし、デバッグ情報のAccept-Languageが日本のものになっていて、それでもなお検索結果が英語のものである場合、ちょっと原因は分かりませんがそういうものであると受け入れるしかなさそうです。

その場合の別路線での対処方法ですが、Googleのサービスの場合、URLのパラメータで表示言語を変更できるかもしれないので、以下の記事を参考に「gl」や「hl」パラメータを加えてみるともしかしたら変わるかもしれません。

https://www.suzukikenichi.com/blog/you-must-definitely-know-gl-parameter-and-hl-parameter/

これでもダメな場合は・・・

Proxyサーバー経由か日本国内のサーバーからアクセスしかなさそうな気がします。

**Comment by parmalatinter** [comment]
「gl」や「hl」パラメータを加えて際のDebug情報です。
結果的に言いますと、英語が表示されてしまいました...。

下記アプリのを表示した際のログです。
https://google-shopping-scraping.herokuapp.com/?name=ps3

 [DEBUG]: 
   uri:     https://www.google.co.jp/search?q=ps3&oq=ps3&source=lnms&tbm=shop&sa=X&hl=ja&gl=jp&start=0
2018-05-04T05:28:18.866734+00:00 app[web.1]:   method:  GET
   headers: 
     Host:            www.google.co.jp
     accept-language: ja-JP
     user-agent:      Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
     accept:          text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8

**Comment by ktty1220** [comment]
こちらでも色々と試してみました。

herokuではないですが、海外のサーバーにexpressを設置してcheerio-httpcliで問題のページを見に行った所、やはり英語版のページになっていました。

しかし、ショップ検索ではなく通常のWEB検索ではちゃんと日本語の検索結果が返ってきました。

また、問題のページの「hl」を「en」に、「gl」を「us」にして普通に日本からブラウザでアクセスした所、ページの表示自体は英語になっていましたが、検索結果が日本語のままでした。

![_002](https://user-images.githubusercontent.com/2086147/39615786-f7f54c66-4fb2-11e8-90e2-111afe5bfce3.png)

このことから考えるとショップ検索で言語指定が無視された結果が返ってくるのは、現状のGoogleの仕様なのではないかと思います。

なので、今のところの対策としてはやはり日本のサーバーから、もしくは日本のサーバー経由でアクセスする他なさそうです。

**Comment by parmalatinter** [comment]
色々調べて頂きありがとう御座います。
Googleの仕様ということで、こればかりはどうしようもないですね。
国内サーバーを検討してみます！

**Comment by parmalatinter** [comment]
Herokuでは一応、地域(region)を変えられるんですが、結構な額なんです😥。

**Comment by ktty1220** [comment]
ショップ検索のこの挙動はバグなんじゃないかと最初は思いましたが、買い物をするという目的の検索であると考えると、各ショップの海外発送の対応状況や送料の観点から、言語設定の国のショップよりもアクセス元の国のショップ情報を優先して表示するのはなんか納得がいくような気がします。

ググッてみると「日本からアメリカのGoogleショッピング検索ができない」という今回とは逆パターンで同じような事例が2016年頃から散見されるので、バグではなくGoogleが意図的にこのような仕様にしているものと思われます。

※解決方法も載ってたりしますが、位置情報やIPアドレスを偽装するといったJavaScript単体でどうにかできるようなものではなかったので、今回の件の助けにはならなさそうです。

というわけで、（どうにもならないという意味で）一応解決したのでIssueを閉じさせてもらいます。

**Comment by parmalatinter** [comment]
ありがとう御座いました！
Googleショッピングなかなか手強いですね。
ある意味海外からのスクレイピング防止に使えそうな気がしました。ありがとう御座いました。
