### ISSUE TITLE
Type 'CheerioStaticEx' has no call signatures.などのエラーが出る

### ISSUE THREAD

**Issue by forest1102** [ktty1220/cheerio-httpcli#37]
cheerio-httpcliを0.8.0にアップデートして、`client.fork()`等の機能を使いたいのですが、0.8.0にすると、`Type 'CheerioStaticEx' has no call signatures.`などのエラーが出ます。
原因として私が考えるのは、cheerioのオブジェクト名が`CheerioStaticEx`が`Root`などのように変更されているためだと思います。

コード

```typescript
import * as client from 'cheerio-httpcli'

client
  .fetch('example.com')
  .then(({ $ }) => $('a'))
  .catch(err => console.log(err))
```

以下にpackage.jsonを載せます

```:package.json
{
  "name": "test-cheeriohttpcli",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cheerio-httpcli": "^0.8.1"
  }
}
```

**Comment by forest1102** [comment]
すいません。  
こちらのエラーですが、`npm i @types/cheerio@0.22.18`としたら、エラーは消えました。

**Comment by ktty1220** [comment]
解決したようで何よりですが、一応原因と対策をまとめておきます。

`cheerio-httpcli`で動作確認済みの`@types/cheerio`と最近の`@types/cheerio`の間で内部構造に大幅な変更が入って別物になっているのが原因のようです。

`cheerio-httpcli`での対応は近日中に行いますが、現時点での解決策を以下にまとめておきます。

1. `dependencies`にバージョンを固定した`@types/cheerio`を指定する
  `cheerio-httpcli`で動作確認済みのバージョンは`0.22.18`です。
2. `package.json`に`resolutions`というフィールドを追加し、1と同じ記述を追加する
  `yarn`を使用する場合はこちらの設定も必要です(<https://yuta-yamamoto.hatenablog.com/entry/2018/11/26/185757>)。
3. `package-lock.json`や`yarn.lock`、`node_modules`ディレクトリを削除する
4. `npm install`や`yarn install`でパッケージ全体の再インストールを行う

```diff
{
  "name": "test-cheeriohttpcli",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
+  "@types/cheerio": "0.22.18",
   "cheerio-httpcli": "^0.8.1"
  }
+ "resolutions": {
+   "@types/cheerio": "0.22.18"
+ }
}
```
